In [21]:
result = 5+2+2+1+2+5+5+15+6+6

In [22]:
print(result)
temp = []

49


In [23]:
while result <= 53:
    result += .124
    print(result)
    temp.append(result)

49.124
49.248000000000005
49.37200000000001
49.49600000000001
49.62000000000001
49.744000000000014
49.868000000000016
49.99200000000002
50.11600000000002
50.24000000000002
50.364000000000026
50.48800000000003
50.61200000000003
50.73600000000003
50.860000000000035
50.98400000000004
51.10800000000004
51.23200000000004
51.356000000000044
51.48000000000005
51.60400000000005
51.72800000000005
51.852000000000054
51.976000000000056
52.10000000000006
52.22400000000006
52.34800000000006
52.472000000000065
52.59600000000007
52.72000000000007
52.84400000000007
52.968000000000075
53.09200000000008


In [24]:
import numpy as np

temp_arr = np.array(temp)
print(temp_arr)

temp_arr *= 4
print(temp_arr)

temp_arr.sum()

[ 49.124  49.248  49.372  49.496  49.62   49.744  49.868  49.992  50.116
  50.24   50.364  50.488  50.612  50.736  50.86   50.984  51.108  51.232
  51.356  51.48   51.604  51.728  51.852  51.976  52.1    52.224  52.348
  52.472  52.596  52.72   52.844  52.968  53.092]
[ 196.496  196.992  197.488  197.984  198.48   198.976  199.472  199.968
  200.464  200.96   201.456  201.952  202.448  202.944  203.44   203.936
  204.432  204.928  205.424  205.92   206.416  206.912  207.408  207.904
  208.4    208.896  209.392  209.888  210.384  210.88   211.376  211.872
  212.368]


6746.2560000000058

In [25]:

temp_arr.tolist()


[196.496,
 196.99200000000002,
 197.48800000000003,
 197.98400000000004,
 198.48000000000005,
 198.97600000000006,
 199.47200000000007,
 199.96800000000007,
 200.46400000000008,
 200.9600000000001,
 201.4560000000001,
 201.9520000000001,
 202.44800000000012,
 202.94400000000013,
 203.44000000000014,
 203.93600000000015,
 204.43200000000016,
 204.92800000000017,
 205.42400000000018,
 205.9200000000002,
 206.4160000000002,
 206.9120000000002,
 207.40800000000021,
 207.90400000000022,
 208.40000000000023,
 208.89600000000024,
 209.39200000000025,
 209.88800000000026,
 210.38400000000027,
 210.88000000000028,
 211.3760000000003,
 211.8720000000003,
 212.3680000000003]

In [26]:
matt = [1,2,3,4,5]

In [27]:
cole = [34,25,64,77,86]

In [29]:
flop = np.array([matt, cole])
print(flop)

[[ 1  2  3  4  5]
 [34 25 64 77 86]]


In [31]:
print(np.sum(flop, axis=0))

[35 27 67 81 91]


In [32]:
print(np.sum(flop, axis=1))

[ 15 286]


In [33]:
matt = np.array(matt)
cole = np.array(cole)

In [34]:
matt * cole

array([ 34,  50, 192, 308, 430])